/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomNavigation: typeof import('./components/BottomNavigation.vue')['default']
    ChapterPageEdit: typeof import('./components/ChapterPageEdit.vue')['default']
    ChapterPageRead: typeof import('./components/ChapterPageRead.vue')['default']
    ComicGallery: typeof import('./components/ComicGallery.vue')['default']
    CustomListDialog: typeof import('./components/CustomListDialog.vue')['default']
    CustomSelect: typeof import('./components/CustomSelect.vue')['default']
    DictionaryEditDialog: typeof import('./components/DictionaryEditDialog.vue')['default']
    DictionaryList: typeof import('./components/DictionaryList.vue')['default']
    DropdownButton: typeof import('./components/DropdownButton.vue')['default']
    FilesTree: typeof import('./components/FilesTree.vue')['default']
    FilesTreeItem: typeof import('./components/FilesTreeItem.vue')['default']
    NavigationDrawer: typeof import('./components/NavigationDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
