/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/comics/[id]/': RouteRecordInfo<'/comics/[id]/', '/comics/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/comics/[id]/edit': RouteRecordInfo<'/comics/[id]/edit', '/comics/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/comics/[id]/read': RouteRecordInfo<'/comics/[id]/read', '/comics/:id/read', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/comics/create': RouteRecordInfo<'/comics/create', '/comics/create', Record<never, never>, Record<never, never>>,
    '/filemanager': RouteRecordInfo<'/filemanager', '/filemanager', Record<never, never>, Record<never, never>>,
    '/parsers/': RouteRecordInfo<'/parsers/', '/parsers', Record<never, never>, Record<never, never>>,
    '/parsers/[id]': RouteRecordInfo<'/parsers/[id]', '/parsers/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/parsers/create': RouteRecordInfo<'/parsers/create', '/parsers/create', Record<never, never>, Record<never, never>>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>>,
  }
}
