/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/authors': RouteRecordInfo<'/authors', '/authors', Record<never, never>, Record<never, never>>,
    '/backups': RouteRecordInfo<'/backups', '/backups', Record<never, never>, Record<never, never>>,
    '/chapters/[id]/edit': RouteRecordInfo<'/chapters/[id]/edit', '/chapters/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/chapters/[id]/read': RouteRecordInfo<'/chapters/[id]/read', '/chapters/:id/read', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/comics/[id]/': RouteRecordInfo<'/comics/[id]/', '/comics/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/comics/[id]/edit': RouteRecordInfo<'/comics/[id]/edit', '/comics/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/comics/[id]/override-edit': RouteRecordInfo<'/comics/[id]/override-edit', '/comics/:id/override-edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/debug': RouteRecordInfo<'/debug', '/debug', Record<never, never>, Record<never, never>>,
    '/languages': RouteRecordInfo<'/languages', '/languages', Record<never, never>, Record<never, never>>,
    '/parsers/': RouteRecordInfo<'/parsers/', '/parsers', Record<never, never>, Record<never, never>>,
    '/parsers/[id]/': RouteRecordInfo<'/parsers/[id]/', '/parsers/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/parsers/[id]/edit': RouteRecordInfo<'/parsers/[id]/edit', '/parsers/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>>,
    '/tags': RouteRecordInfo<'/tags', '/tags', Record<never, never>, Record<never, never>>,
  }
}
